run:
  timeout: 5m
  allow-parallel-runners: true
  build-tags:
    - integration

issues:
  # don't skip warning about doc comments
  # don't exclude the default set of lint
  exclude-use-default: false

linters:
  disable-all: true
  enable:
  - dupl
  - errcheck
  - gci
  - goconst
  - gocyclo
  - godot
  - gofmt
  - goimports
  - gosimple
  - govet
  - ineffassign
  - lll
  - misspell
  - nakedret
  - nolintlint
  - revive
  - staticcheck
  - typecheck
  - unconvert
  - unparam
  - unused

linters-settings:
  gci:
    sections:
    - standard
    - default
    - blank
    - dot
    - prefix(k8s.io,sigs.k8s.io)

  nolintlint:
    require-explanation: true
    require-specific: true

  revive:
    rules:
    - name: comment-spacings
