apiVersion: v1
kind: Secret
metadata:
  name: objectstorage-provisioner
  labels:
    app.kubernetes.io/part-of: container-object-storage-interface
    app.kubernetes.io/component: driver-sample
    app.kubernetes.io/version: main
    app.kubernetes.io/name: cosi-driver-sample
type: Opaque
stringData:
  OBJECT_SCALE_GATEWAY: "http://10.243.23.16:32585"
  OBJECT_STORE_ENDPOINT: "http://10.243.23.16:31651"
  OBJECT_STORE_ACCESS_KEY: "OKIA53EA314F369AAAFA"
  OBJECT_STORE_SECRET_KEY: "1fixtMYMBr+9RpfOMn2ePpPZT30RqwHkTia1ypVM"
  V: "3"
