---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: driver
  labels:
    app.kubernetes.io/name: sample.objectstorage.k8s.io
    app.kubernetes.io/instance: sample.objectstorage.k8s.io
    app.kubernetes.io/part-of: cosi-driver-sample
    app.kubernetes.io/component: cosi-driver
    app.kubernetes.io/managed-by: kustomize
subjects:
  - kind: ServiceAccount
    name: driver
    namespace: system
roleRef:
  kind: ClusterRole
  name: foo-linode-cosi-driver
  apiGroup: rbac.authorization.k8s.io
