---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: driver
  namespace: system
  labels:
    app.kubernetes.io/name: sample.objectstorage.k8s.io
    app.kubernetes.io/instance: sample.objectstorage.k8s.io
    app.kubernetes.io/part-of: cosi-driver-sample
    app.kubernetes.io/component: cosi-driver
    app.kubernetes.io/managed-by: kustomize
