---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cosi-driver-sample
  labels:
    app.kubernetes.io/part-of: cosi-driver-sample
    app.kubernetes.io/component: driver
    app.kubernetes.io/name: cosi-driver-sample
