---
apiVersion: v1
kind: Pod
metadata:
  name: object-storage-consumer
spec:
  containers:
    - name: app
      image: docker.io/busybox:latest
      command: ["sh", "-c", "sleep 9999"]
      volumeMounts:
        - name: cosi-secrets
          mountPath: /data/cosi
  volumes:
    - name: cosi-secrets
      csi:
        driver: objectstorage.k8s.io
        volumeAttributes:
          bar-name: cosi-driver-sample-bar
          bar-namespace: default
