apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./driver.yaml
images:
- name: driver
  newName: gcr.io/k8s-staging-sig-storage/cosi-driver-sample
  newTag: main
- name: sidecar
  newName: gcr.io/k8s-staging-sig-storage/objectstorage-sidecar/objectstorage-sidecar
  newTag: v20221117-v0.1.0-22-g0e67387
