apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: web
    image: k8s.gcr.io/nginx-slim:0.8
    imagePullPolicy: Always
    ports:
    - name: web
      containerPort: 80
      protocol: TCP
    volumeMounts:
    - name: cosi-secrets
      mountPath: /data/cosi
    env:
      - name: PORT
        value: "3001"
  volumes:
  - name: cosi-secrets
    csi:
      driver: objectstorage.k8s.io
      volumeAttributes:
        bar-name: sample-bar
